security:
    password_hashers:
        App\Entity\Client:
            algorithm: bcrypt
        App\Entity\Member:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            anonymous: true
        main:
            lazy: true
            security: false
            anonymous: true
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Member
                property: username
        # - { path: ^/profile, roles: ROLE_USER }
